# Generated by Django 3.2.7 on 2021-09-07 05:52

import blacklist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kolasid', models.CharField(max_length=70)),
                ('count', models.IntegerField()),
                ('places', models.JSONField(verbose_name=blacklist.models.jsonfield_default)),
                ('detail', models.TextField()),
            ],
        ),
    ]
