# Generated by Django 3.2.7 on 2021-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_alter_personmodel_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='no',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
