# Generated by Django 3.2.7 on 2021-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_auto_20210909_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
