# Generated by Django 3.2.7 on 2021-09-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
